name: Test workflow

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: test
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          df -hT $PWD
          pwd
          ls -al
          id -u
