name: Test workflow

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: test
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          df -hT $PWD
          pwd
          ls -al
          id -u

      - name: Prepare for packing firmware
        if: env.UPLOAD_PACK == 'true' && !cancelled()
        run: |
          git clone --depth=1 https://github.com/unifreq/openwrt_packit opt
          mkdir -p opt/kernel
          mkdir -p opt/tmp
          mv pack/kernel/* opt/kernel/
          [ -e $MAKE_ENV_FILE ] && mv -f pack/$MAKE_ENV_FILE opt/make.env
          pwd